language: python

python:
    - 2.7
    - 3.5
    - 3.6

branches:
    only:
        - master

before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
    - pip install coverage
    - pip install coveralls
    - pip install pylint
    - pip install -r requirements.txt

script:
    - coverage run -m unittest discover -s seattlecollision/tests

after_success:
    - coverage report
    - coveralls


